### ISSUE TITLE
[Epic] Metrics 

### ISSUE THREAD

**Issue by garrensmith** [prisma/client-planning#2]
## Overview
This is the Epic to track the Metrics Work 

The Technical Spec covers work breakdown and cross function team work

https://www.notion.so/prismaio/Metrics-for-Observability-7744be00a8f8481784d06a4c3c4619d9?d=023376dc66ff4ccf9c64016756b26baf

Metrics Tickets:

- [x] https://github.com/prisma/prisma/issues/12874
- [x] https://github.com/prisma/prisma/issues/12875
- [x] https://github.com/prisma/prisma/issues/12876
- [x] https://github.com/prisma/prisma/issues/12877

**Comment by janpio** [comment]
Seems to be all done 👍
