### ISSUE TITLE
Stabilize filterJson

### ISSUE THREAD

**Issue by dpetrick** [prisma/client-planning#20]
# Overview
Tracking ticket for: 
- https://github.com/prisma/prisma/issues/7135

# Work items
- [x] Coordinate documentation work: https://github.com/prisma/docs/issues/3176
- [x] Collect issues that need fixing or that we won't fix.
- [x] Remove feature flag

**Comment by cprieto** [comment]
Done with https://github.com/prisma/prisma-engines/pull/2958
