### ISSUE TITLE
[Epic] Tracing

### ISSUE THREAD

**Issue by garrensmith** [prisma/client-planning#21]
The aim is to consolidate the tracing we have in the client, document it and make it easy to use for Prisma Client users. 

Project Board is https://github.com/orgs/prisma/projects/72

## Work Breakdown
- Tracking of the actual work items happens here.
- [x]  https://github.com/prisma/prisma/issues/13360
- [x] https://github.com/prisma/prisma/issues/13501
- [x] https://github.com/prisma/prisma/issues/13502
- [x] https://github.com/prisma/docs/issues/3414

**Comment by garrensmith** [comment]
This shipped today 🎉
