### ISSUE TITLE
Do not crash on over/underflowing integers

### ISSUE THREAD

**Issue by dpetrick** [prisma/client-planning#7]
# Overview
Tracking ticket for: https://www.notion.so/prismaio/Technical-Design-Documents-e2db1d4f05ff425283bc444ff850c28d?p=0d3c585cc7ee4d8ba8d9f2c8e9b20dc7

# Work items
- [x] Engine side ticket: https://github.com/prisma/prisma-engines/pull/2921
- [x] TypeScript integration: https://github.com/prisma/client-planning/issues/26
- [x] Documentation changes: https://github.com/prisma/docs/issues/3151
